# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{iphone-style-checkboxes}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Thomas Reynolds"]
  s.date = %q{2010-08-17}
  s.email = %q{tdreyno@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/iphone-style-checkboxes.rb",
     "stylesheets/_iphone-style-checkboxes.sass",
     "templates/project/iphone-style-checkboxes/off.png",
     "templates/project/iphone-style-checkboxes/on.png",
     "templates/project/iphone-style-checkboxes/slider.png",
     "templates/project/iphone-style-checkboxes/slider_center.png",
     "templates/project/iphone-style-checkboxes/slider_left.png",
     "templates/project/iphone-style-checkboxes/slider_right.png",
     "templates/project/iphone-style-example.sass",
     "templates/project/manifest.rb",
     "test/helper.rb",
     "test/test_compass-iphone-style-checkboxes.rb"
  ]
  s.homepage = %q{http://github.com/tdreyno/compass-iphone-style-checkboxes}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Compass plugin for the iPhone-style checkboxes}
  s.test_files = [
    "test/helper.rb",
     "test/test_compass-iphone-style-checkboxes.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<compass>, [">= 0.10"])
    else
      s.add_dependency(%q<compass>, [">= 0.10"])
    end
  else
    s.add_dependency(%q<compass>, [">= 0.10"])
  end
end

